name: Confirm tests run successfully

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Verify tests pass

    runs-on: ubuntu-latest

    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        compose:
          - RHEL-9.5.0-Nightly
          - Fedora-40-Updated
          - CentOS-Stream-9
        dotnet_version:
          - "8.0"
        architecure:
          - x86_64
          - s390x
    
    steps:
      - name: Schedule test on Testing Farm
        uses: sclorg/testing-farm-as-github-action@v3
        with:
          api_key: ${{ secrets.TF_API }}
          compose: ${{ matrix.compose }}
          arch: ${{ matrix.architecure }}
          tmt_plan_regex: "regular-tests"
          pull_request_status_name: ${{ matrix.compose }} + " - " ${{ matrix.dotnet_version }}

